import { Inter } from 'next/font/google'
import './globals.css'
import {AppProvider} from '@/utils/AppProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Reddit - Dive into anything',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  
  return (
      <html lang="en">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
          <body className={inter.className}>
            <AppProvider>
                {children}
            </AppProvider>
            </body>
      </html>
  )
}